version: "3.8"

services:
  backend:
    build: ./back-end
    container_name: node_backend
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
    working_dir: /app
    command: node app.js

  frontend:
    build: ./my-next-app
    container_name: next_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./my-next-app:/app
      - /app/node_modules
    working_dir: /app
    command: yarn dev
    depends_on:
      - backend
